# Generated by Django 3.0.6 on 2023-05-11 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='name')),
                ('type', models.CharField(choices=[('B', 'Boolean'), ('I', 'Integer'), ('S', 'String')], max_length=1, verbose_name='type')),
                ('default', models.CharField(blank=True, max_length=254, verbose_name='default')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentsets', models.ManyToManyField(blank=True, to='equipment.EquipmentSet', verbose_name='equipmentsets')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='equipment')),
                ('equipment_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentSet', verbose_name='equipment_set')),
            ],
            options={
                'unique_together': {('equipment_set', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=254, verbose_name='comment')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('value', models.CharField(max_length=254, verbose_name='value')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='equipment')),
                ('equipmentholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentHolder', verbose_name='equipmentholder')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'unique_together': {('equipmentholder', 'equipment')},
            },
        ),
    ]
