# Generated by Django 3.0.6 on 2023-05-11 00:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import login.mixins
import login.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=254, unique=True, verbose_name='client_id')),
                ('status', models.CharField(choices=[('O', 'online'), ('F', 'offline'), ('D', 'disconnected'), ('R', 'reconnected')], max_length=1, verbose_name='status')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('ambulance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulance.Ambulance', verbose_name='ambulance')),
                ('hospital', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital', verbose_name='hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dispatcher', models.BooleanField(default=False, verbose_name='is_dispatcher')),
                ('is_guest', models.BooleanField(default=False, verbose_name='is_guest')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            bases=(login.mixins.ClearPermissionCacheMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TokenLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(default=login.models.unique_slug_generator, unique=True)),
                ('url', models.URLField(blank=True, max_length=512, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='created_on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=254, verbose_name='password')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='created_on')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
                ('priority', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='priority')),
                ('can_sms_notifications', models.BooleanField(default=False, verbose_name='can_sms_notifications')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group')),
            ],
            bases=(login.mixins.ClearPermissionCacheMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GroupHospitalPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True, verbose_name='can_read')),
                ('can_write', models.BooleanField(default=False, verbose_name='can_write')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital', verbose_name='hospital')),
            ],
            bases=(login.mixins.ClearPermissionCacheMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GroupAmbulancePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True, verbose_name='can_read')),
                ('can_write', models.BooleanField(default=False, verbose_name='can_write')),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.Ambulance', verbose_name='ambulance')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group')),
            ],
            bases=(login.mixins.ClearPermissionCacheMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'online'), ('F', 'offline'), ('D', 'disconnected'), ('R', 'reconnected')], max_length=1, verbose_name='status')),
                ('activity', models.CharField(choices=[('HS', 'handshake'), ('AI', 'vehicle login'), ('AO', 'vehicle logout'), ('TL', 'vehicle stop location'), ('SL', 'vehicle start location'), ('HI', 'hospital login'), ('HO', 'hospital logout')], max_length=2, verbose_name='activity')),
                ('details', models.CharField(blank=True, max_length=100, verbose_name='details')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client', verbose_name='client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='UserHospitalPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True, verbose_name='can_read')),
                ('can_write', models.BooleanField(default=False, verbose_name='can_write')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital', verbose_name='hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('user', 'hospital')},
            },
            bases=(login.mixins.ClearPermissionCacheMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserAmbulancePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True, verbose_name='can_read')),
                ('can_write', models.BooleanField(default=False, verbose_name='can_write')),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.Ambulance', verbose_name='ambulance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('user', 'ambulance')},
            },
            bases=(login.mixins.ClearPermissionCacheMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='groupprofile',
            index=models.Index(fields=['priority'], name='login_group_priorit_8c2d80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouphospitalpermission',
            unique_together={('group', 'hospital')},
        ),
        migrations.AlterUniqueTogether(
            name='groupambulancepermission',
            unique_together={('group', 'ambulance')},
        ),
    ]
