# Generated by Django 3.0.6 on 2026-02-10 11:50

from django.db import migrations, models
import django.db.models.deletion
import login.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('ambulance', '0001_initial'),
        ('login', '0006_auto_20241120_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Organization', verbose_name='organization')),
            ],
            bases=(login.mixins.ClearPermissionCacheMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationHospitalPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True, verbose_name='can_read')),
                ('can_write', models.BooleanField(default=False, verbose_name='can_write')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital', verbose_name='hospital')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Organization', verbose_name='organization')),
            ],
            options={
                'unique_together': {('organization', 'hospital')},
            },
            bases=(login.mixins.ClearPermissionCacheMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationAmbulancePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True, verbose_name='can_read')),
                ('can_write', models.BooleanField(default=False, verbose_name='can_write')),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.Ambulance', verbose_name='ambulance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Organization', verbose_name='organization')),
            ],
            options={
                'unique_together': {('organization', 'ambulance')},
            },
            bases=(login.mixins.ClearPermissionCacheMixin, models.Model),
        ),
    ]
