# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 22:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulances',
            fields=[
                ('license_plate', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=254)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-117.0382, 32.5149, srid=4326), srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ambulances',
            name='reporter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulances.Reporter'),
        ),
    ]
