# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulances',
            name='reporter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulances.Reporter'),
        ),
    ]
