# Generated by Django 3.0.6 on 2023-05-11 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ambulance.Location')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('equipmentholder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentHolder', verbose_name='equipmentholder')),
            ],
            options={
                'abstract': False,
            },
            bases=('ambulance.location',),
        ),
    ]
