# Generated by Django 3.0.6 on 2023-05-11 00:16

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import emstrack.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=254, verbose_name='comment')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='identifier')),
                ('capability', models.CharField(choices=[('B', 'Basic'), ('A', 'Advanced'), ('R', 'Rescue'), ('M', 'Medic'), ('S', 'Supervisor'), ('P', 'Professional First Responder'), ('C', 'Community First Responder')], max_length=1, verbose_name='capability')),
                ('status', models.CharField(choices=[('UK', 'Unknown'), ('AV', 'Available'), ('OS', 'Out of service'), ('PB', 'Incident bound'), ('AP', 'At incident'), ('HB', 'Hospital bound'), ('AH', 'At hospital'), ('BB', 'Base bound'), ('AB', 'At base'), ('WB', 'Waypoint bound'), ('AW', 'At waypoint')], default='UK', max_length=2, verbose_name='status')),
                ('orientation', models.FloatField(default=0.0, verbose_name='orientation')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-117.0382, 32.5149, srid=4326), srid=4326, verbose_name='location')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('equipmentholder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentHolder', verbose_name='equipmentholder')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
            bases=(emstrack.mixins.PublishMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AmbulanceCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=254, verbose_name='comment')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('status', models.CharField(choices=[('R', 'Requested'), ('A', 'Accepted'), ('D', 'Declined'), ('S', 'Suspended'), ('C', 'Completed')], default='R', max_length=1, verbose_name='status')),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.Ambulance', verbose_name='ambulance')),
            ],
            bases=(emstrack.mixins.PublishMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=254, verbose_name='comment')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Started'), ('E', 'Ended')], default='P', max_length=1, verbose_name='status')),
                ('details', models.CharField(default='', max_length=500, verbose_name='details')),
                ('priority', models.CharField(choices=[('A', 'Resuscitation'), ('B', 'Emergent'), ('C', 'Urgent'), ('D', 'Less urgent'), ('E', 'Not urgent'), ('O', 'Omega')], default='E', max_length=1, verbose_name='priority')),
                ('pending_at', models.DateTimeField(blank=True, null=True, verbose_name='pending_at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started_at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'abstract': False,
            },
            bases=(emstrack.mixins.PublishMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CallPriorityClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
            ],
        ),
        migrations.CreateModel(
            name='CallRadioCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='number')),
                ('street', models.CharField(blank=True, max_length=254, verbose_name='street')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='unit')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='neighborhood')),
                ('city', models.CharField(default='Tijuana', max_length=100, verbose_name='city')),
                ('state', models.CharField(default='BCN', max_length=4, verbose_name='state')),
                ('zipcode', models.CharField(blank=True, max_length=12, verbose_name='zipcode')),
                ('country', models.CharField(default='MX', max_length=2, verbose_name='country')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-117.0382, 32.5149, srid=4326), srid=4326, verbose_name='location')),
                ('comment', models.CharField(blank=True, max_length=254, verbose_name='comment')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('name', models.CharField(blank=True, max_length=254, verbose_name='name')),
                ('type', models.CharField(choices=[('b', 'Base'), ('a', 'AED'), ('i', 'Incident'), ('h', 'Hospital'), ('w', 'Waypoint'), ('o', 'Other')], max_length=1, verbose_name='type')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='name')),
                ('center', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='center')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=254, verbose_name='comment')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('status', models.CharField(choices=[('C', 'Created'), ('V', 'Visiting'), ('D', 'Visited'), ('S', 'Skipped')], default='C', max_length=1, verbose_name='status')),
                ('ambulance_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.AmbulanceCall', verbose_name='ambulance_call')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulance.Location', verbose_name='location')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'unique_together': {('ambulance_call', 'order')},
            },
            bases=(emstrack.mixins.PublishMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WaypointHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=254, verbose_name='comment')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('status', models.CharField(choices=[('C', 'Created'), ('V', 'Visiting'), ('D', 'Visited'), ('S', 'Skipped')], max_length=1, verbose_name='status')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.Waypoint', verbose_name='waypoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254, verbose_name='name')),
                ('age', models.IntegerField(null=True, verbose_name='age')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.Call', verbose_name='call')),
            ],
            bases=(emstrack.mixins.PublishMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CallPriorityCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('A', 'Resuscitation'), ('B', 'Emergent'), ('C', 'Urgent'), ('D', 'Less urgent'), ('E', 'Not urgent'), ('O', 'Omega')], default='E', max_length=1, verbose_name='priority')),
                ('suffix', models.CharField(max_length=10, verbose_name='suffix')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.CallPriorityClassification', verbose_name='prefix')),
            ],
        ),
        migrations.CreateModel(
            name='CallNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=254, verbose_name='comment')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.Call', verbose_name='call')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
            bases=(emstrack.mixins.PublishMixin, models.Model),
        ),
        migrations.AddField(
            model_name='call',
            name='priority_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulance.CallPriorityCode', verbose_name='priority_code'),
        ),
        migrations.AddField(
            model_name='call',
            name='radio_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulance.CallRadioCode', verbose_name='radio_code'),
        ),
        migrations.AddField(
            model_name='call',
            name='sms_notifications',
            field=models.ManyToManyField(related_name='sms_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.CreateModel(
            name='AmbulanceUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=254, verbose_name='comment')),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_on')),
                ('capability', models.CharField(choices=[('B', 'Basic'), ('A', 'Advanced'), ('R', 'Rescue'), ('M', 'Medic'), ('S', 'Supervisor'), ('P', 'Professional First Responder'), ('C', 'Community First Responder')], max_length=1, verbose_name='capability')),
                ('status', models.CharField(choices=[('UK', 'Unknown'), ('AV', 'Available'), ('OS', 'Out of service'), ('PB', 'Incident bound'), ('AP', 'At incident'), ('HB', 'Hospital bound'), ('AH', 'At hospital'), ('BB', 'Base bound'), ('AB', 'At base'), ('WB', 'Waypoint bound'), ('AW', 'At waypoint')], default='UK', max_length=2, verbose_name='status')),
                ('orientation', models.FloatField(default=0.0, verbose_name='orientation')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-117.0382, 32.5149, srid=4326), srid=4326, verbose_name='location')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.Ambulance', verbose_name='ambulance')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceCallHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=254, verbose_name='comment')),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_on')),
                ('status', models.CharField(choices=[('R', 'Requested'), ('A', 'Accepted'), ('D', 'Declined'), ('S', 'Suspended'), ('C', 'Completed')], max_length=1, verbose_name='status')),
                ('ambulance_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.AmbulanceCall', verbose_name='ambulance_call')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ambulancecall',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.Call', verbose_name='call'),
        ),
        migrations.AddField(
            model_name='ambulancecall',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated_by'),
        ),
        migrations.AddIndex(
            model_name='ambulanceupdate',
            index=models.Index(fields=['ambulance', 'timestamp'], name='ambulance_timestamp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ambulancecall',
            unique_together={('call', 'ambulance')},
        ),
    ]
